version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    restart: always
    depends_on:
      - postgres
    ports:
      - '8000:80'
    networks:
      - app-network
  postgres:
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app-network

networks:
  app-network: